name: CI

on:
  push:
    branches:
      - master
      - refactor
  pull_request:
    branches:
      - master
      - refactor
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: '1.20'
        cache: false
    - name: Golang lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53
        args: --timeout=10m --allow-parallel-runners -p bugs -p sql -p unused -p format -v
    
    - name: Test
      run: go test -v ./...
